import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    title: "AgriPulse",
    tagline: "Futuristic Mandi Intelligence & Agricultural SaaS",
    dashboard: "Farmer Dashboard",
    mandiExplorer: "Live Mandi Explorer",
    comparisonView: "Smart Transport & Profit Comparison",
    marketplace: "Direct Marketplace",
    priceAlerts: "Price Alerts",
    cropHealth: "AI Crop Health",
    weather: "Weather Advisory",
    schemes: "Govt Schemes",
    myListings: "My Active Produce Listings",
    addListing: "+ Add New Produce Listing",
    bestPriceNearMe: "Best Price Near Me",
    searchCrop: "Search Commodity (e.g. Onion, Wheat)...",
    filterState: "Filter State",
    filterDistrict: "Filter District",
    modalPrice: "Modal Price",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    distance: "Distance",
    transportCost: "Est. Transport Cost",
    netProfit: "Net Profit Estimate",
    recommendation: "Recommendation",
    login: "Phone OTP Login",
    profile: "Farmer Profile",
    soldStatus: "Mark Sold",
    activeStatus: "Active",
    askingPrice: "Asking Price (₹/Quintal)",
    quantity: "Quantity (Quintals)",
    qualityGrade: "Quality Grade",
    cropName: "Crop Name",
    variety: "Variety",
    location: "Farm Location",
    setAlert: "Set Target Price Alert",
    scanCrop: "Scan Crop Leaf for Disease",
    speakAudio: "Listen Audio",
  },
  hi: {
    title: "एग्रीपल्स",
    tagline: "भविष्य की मंडी मूल्य एवं कृषि प्लेटफॉर्म",
    dashboard: "किसान डैशबोर्ड",
    mandiExplorer: "लाइव मंडी भाव",
    comparisonView: "परिवहन एवं शुद्ध लाभ तुलना",
    marketplace: "सीधा बाज़ार",
    priceAlerts: "मूल्य अलर्ट",
    cropHealth: "AI फसल स्वास्थ्य",
    weather: "मौसम सलाह",
    schemes: "सरकारी योजनाएं",
    myListings: "मेरी सक्रिय फसल सूची",
    addListing: "+ नई फसल जोड़ें",
    bestPriceNearMe: "मेरे पास सबसे अच्छा भाव",
    searchCrop: "फसल खोजें (जैसे प्याज़, गेहूँ)...",
    filterState: "राज्य चुनें",
    filterDistrict: "ज़िला चुनें",
    modalPrice: "औसत भाव",
    minPrice: "न्यूनतम भाव",
    maxPrice: "अधिकतम भाव",
    distance: "दूरी",
    transportCost: "अनुमानित भाड़ा",
    netProfit: "शुद्ध लाभ अनुमान",
    recommendation: "सलाह",
    login: "फोन OTP लॉगिन",
    profile: "किसान प्रोफाइल",
    soldStatus: "बिक गया",
    activeStatus: "सक्रिय",
    askingPrice: "मांग मूल्य (₹/क्विंटल)",
    quantity: "मात्रा (क्विंटल)",
    qualityGrade: "गुणवत्ता ग्रेड",
    cropName: "फसल नाम",
    variety: "किस्म",
    location: "खेत स्थान",
    setAlert: "लक्ष्य मूल्य अलर्ट सेट करें",
    scanCrop: "फसल रोग स्कैन करें",
    speakAudio: "आवाज सुनें",
  },
  pa: {
    title: "ਐਗਰੀਪਲਸ",
    tagline: "ਲਾਈਵ ਮੰਡੀ ਭਾਅ ਅਤੇ ਖੇਤੀਬਾੜੀ ਪਲੇਟਫਾਰਮ",
    dashboard: "ਕਿਸਾਨ ਡੈਸ਼ਬੋਰਡ",
    mandiExplorer: "ਲਾਈਵ ਮੰਡੀ ਭਾਅ",
    comparisonView: "ਟ੍ਰਾਂਸਪੋਰਟ ਅਤੇ ਸ਼ੁੱਧ ਮੁਨਾਫਾ",
    marketplace: "ਸਿੱਧੀ ਮਾਰਕੀਟ",
    priceAlerts: "ਕੀਮਤ ਅਲਰਟ",
    cropHealth: "AI ਫਸਲ ਸਿਹਤ",
    weather: "ਮੌਸਮ ਜਾਣਕਾਰੀ",
    schemes: "ਸਰਕਾਰੀ ਸਕੀਮਾਂ",
    myListings: "ਮੇਰੀਆਂ ਸਰਗਰਮ ਫਸਲਾਂ",
    addListing: "+ ਨਵੀਂ ਫਸਲ ਸ਼ਾਮਲ ਕਰੋ",
    bestPriceNearMe: "ਮੇਰੇ ਨੇੜੇ ਸਭ ਤੋਂ ਵਧੀਆ ਭਾਅ",
    searchCrop: "ਫਸਲ ਖੋਜੋ (ਜਿਵੇਂ ਕਣਕ, ਪਿਆਜ਼)...",
    filterState: "ਰਾਜ ਚੁਣੋ",
    filterDistrict: "ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ",
    modalPrice: "ਮਾਡਲ ਭਾਅ",
    minPrice: "ਘੱਟੋ-ਘੱਟ ਭਾਅ",
    maxPrice: "ਵੱਧ ਤੋਂ ਵੱਧ ਭਾਅ",
    distance: "ਦੂਰੀ",
    transportCost: "ਕਿਰਾਇਆ",
    netProfit: "ਸ਼ੁੱਧ ਮੁਨਾਫਾ",
    recommendation: "ਸਿਫਾਰਿਸ਼",
    login: "ਫੋਨ OTP ਲੌਗਇਨ",
    profile: "ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ",
    soldStatus: "ਵਿਕ ਗਿਆ",
    activeStatus: "ਸਰਗਰਮ",
    askingPrice: "ਮੰਗ ਕੀਮਤ (₹/ਕੁਇੰਟਲ)",
    quantity: "ਮਾਤਰਾ (ਕੁਇੰਟਲ)",
    qualityGrade: "ਗੁਣਵੱਤਾ",
    cropName: "ਫਸਲ ਦਾ ਨਾਂ",
    variety: "ਕਿਸਮ",
    location: "ਖੇਤ ਦੀ ਜਗ੍ਹਾ",
    setAlert: "ਕੀਮਤ ਅਲਰਟ ਸੈੱਟ ਕਰੋ",
    scanCrop: "ਫਸਲ ਬਿਮਾਰੀ ਸਕੈਨ",
    speakAudio: "ਆਵਾਜ਼ ਸੁਣੋ",
  },
  mr: {
    title: "अ‍ॅग्रीपल्स",
    tagline: "भविष्यातील बाजार भाव आणि कृषी मंच",
    dashboard: "शेतकरी डॅशबोर्ड",
    mandiExplorer: "थेट बाजार भाव",
    comparisonView: "वाहतूक व निव्वळ नफा तुलना",
    marketplace: "थेट बाजारपेठ",
    priceAlerts: "भाव अलर्ट",
    cropHealth: "AI पीक आरोग्य",
    weather: "हवामान अंदाज",
    schemes: "शासकीय योजना",
    myListings: "माझी पिके",
    addListing: "+ नवीन पीक जोडा",
    bestPriceNearMe: "जवळचा सर्वोत्तम दर",
    searchCrop: "पीक शोधा (उदा. कांदा, गहू)...",
    filterState: "राज्य",
    filterDistrict: "जिल्हा",
    modalPrice: "सरासरी दर",
    minPrice: "कमीत कमी दर",
    maxPrice: "जास्तीत जास्त दर",
    distance: "अंतर",
    transportCost: "वाहतूक खर्च",
    netProfit: "निव्वळ नफा",
    recommendation: "शिफारस",
    login: "फोन OTP लॉगिन",
    profile: "शेतकरी प्रोफाइल",
    soldStatus: "विकले",
    activeStatus: "सक्रिय",
    askingPrice: "मागणी दर (₹/क्विंटल)",
    quantity: "प्रमाण (क्विंटल)",
    qualityGrade: "दर्जा",
    cropName: "पिकाचे नाव",
    variety: "वाण",
    location: "शेताचे ठिकाण",
    setAlert: "लक्ष्य दर सेट करा",
    scanCrop: "रोग निदान करा",
    speakAudio: "ऐका",
  },
  te: {
    title: "ఆగ్రిపల్స్",
    tagline: "లైవ్ మార్కెట్ ధరలు మరియు వ్యవసాయ ప్లాట్‌ఫారమ్",
    dashboard: "రైతు డాష్‌బోర్డ్",
    mandiExplorer: "లైవ్ మార్కెట్ ధరలు",
    comparisonView: "రవాణా & నికర లాభం",
    marketplace: "డైరెక్ట్ మార్కెట్",
    priceAlerts: "ధర హెచ్చరికలు",
    cropHealth: "AI పంట ఆరోగ్యం",
    weather: "వాతావరణ సమాచారం",
    schemes: "ప్రభుత్వ పథకాలు",
    myListings: "నా ఉత్పత్తులు",
    addListing: "+ కొత్త ఉత్పత్తి చేర్చండి",
    bestPriceNearMe: "నా దగ్గర బెస్ట్ ధర",
    searchCrop: "పంట శోధించండి...",
    filterState: "రాష్ట్రం",
    filterDistrict: "జిల్లా",
    modalPrice: "సగటు ధర",
    minPrice: "కనిష్ట ధర",
    maxPrice: "గరిష్ట ధర",
    distance: "దూరం",
    transportCost: "రవాణా ఖర్చు",
    netProfit: "నికర లాభం",
    recommendation: "సిఫార్సు",
    login: "ఫోన్ OTP లాగిన్",
    profile: "రైతు ప్రొఫైల్",
    soldStatus: "అమ్ముడైంది",
    activeStatus: "యాక్టివ్",
    askingPrice: "ధర (₹/క్వింటాల్)",
    quantity: "పరిమాణం (క్వింటాళ్ళు)",
    qualityGrade: "క్వాలిటీ గ్రేడ్",
    cropName: "పంట పేరు",
    variety: "రకం",
    location: "పొలం లొకేషన్",
    setAlert: "టార్గెట్ ప్రైస్ అలర్ట్",
    scanCrop: "పంట వ్యాధి స్కానర్",
    speakAudio: "వినండి",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
